services:
  postgres:
    image: postgres:16
    container_name: syscode_postgres
    environment:
      POSTGRES_DB: syscode
      POSTGRES_USER: syscode
      POSTGRES_PASSWORD: syscode
    ports:
      - "5432:5432"
    volumes:
      - syscode_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U syscode -d syscode"]
      interval: 5s
      timeout: 3s
      retries: 20

  liquibase:
    image: liquibase/liquibase:4.24
    container_name: syscode_liquibase
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - --searchPath=/workspace
      - --changeLogFile=changelog.xml
      - --url=jdbc:postgresql://postgres:5432/syscode
      - --username=syscode
      - --password=syscode
      - update
    volumes:
      - ./apps/profile-service/liquibase:/workspace

  address-service:
    build:
      context: ./apps/address-service
      dockerfile: Dockerfile
    container_name: syscode_address_service
    environment:
      PORT: "3001"
      BASIC_AUTH_USERNAME: syscode
      BASIC_AUTH_PASSWORD: syscode
    ports:
      - "3001:3001"

  profile-service:
    build:
      context: ./apps/profile-service
      dockerfile: Dockerfile
    container_name: syscode_profile_service
    depends_on:
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
      address-service:
        condition: service_started
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: syscode
      DB_PASS: syscode
      DB_NAME: syscode
      TYPEORM_SYNC: "false"

      ADDRESS_SERVICE_URL: http://address-service:3001
      ADDRESS_SERVICE_USERNAME: syscode
      ADDRESS_SERVICE_PASSWORD: syscode
    ports:
      - "3000:3000"

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: syscode_web
    depends_on:
      profile-service:
        condition: service_started
    ports:
      - "4200:4200"

volumes:
  syscode_pgdata:
